version: "3.8"
services: 
  mongodb:
    image: mongo
    volumes:
      - mongodbdata:/data/db
    env_file:
      - ./env/mongo.env
    container_name: mongodb
    
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/src:/app/src
    ports:
      - 8000:8000
    env_file:
      - ./env/backend.env
    container_name: backend
    depends_on:
      - mongodb
    
  frontend:
    stdin_open: true
    tty: true
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/src:/app/src
    ports:
      - 3000:3000
    container_name: frontend
    depends_on:
      - backend

volumes:
  mongodbdata:

